language: node_js
node_js: stable
# .travis.yml 配置
cache:
  directories:
    - node_modules

before_install:
- npm install -g hexo-cli

before_script:
# ------------------------------------------------
# 设置github账户信息 注意修改成自己的信息
# ------------------------------------------------
- git config --global user.name "Kai Zhang"
- git config --global user.email rainygoblin@gmail.com
# Make sure to make the output quiet, or else the API token will leak!
# This works because the API key can replace your password.
- sed -i'' "/^ *repo/s~github\.com~${GITHUB_API_KEY}@github.com~" _config.yml

# 安装依赖
install:
- npm install

# 部署的命令
script:
- git submodule init      # 用于更新主题
- git submodule update
- hexo clean
- hexo generate

# 执行的成功后执行
after_success:
- hexo deploy